language: node_js
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install lldb-3.9 liblldb-3.9-dev -y
node_js:
  - "4"
  - "6"
  - "8"
  - "9"
matrix:
  include:
    # Test Node.js master nightly build
    - node_js: "node"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
    # Test Node.js v8-canary nightly build
    - node_js: "node"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary"
  allow_failures:
    # Allow the nightly installs to fail
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary"
branches:
  only:
    - master
script: make _travis
