name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install --only=dev --ignore-scripts
      - name: Run linter
        run: npm run linter
